### ISSUE TITLE
Add documentation for methods 

### ISSUE THREAD

**Issue by srevinsaju** [free-libre-software/sugarappstore#1]
The current python code is unreadable due to numerous typos and and wrong PEP8 syntax. I would be very grateful if you update the README file on the number of processes it is undergoing, so that any new developer is likely to understand it.

**Comment by radiidev** [comment]
I have added code guide of most of the code in README.md for now which should help you get started.

Can you explain what you mean by typo? I have corrected some spelling errors in python code but likely you mean something else

 Also, python code has been modified to make it more readable. However since this is prototype, there needs a lot more changes to be made before committing it to the master branch (including re-evaluating logic). For instance, currently html generation template is hard coded. It should be loaded from external template file and a generic function should be called with template and variables with data that will be embedded.

Can you please list which python style guides are not followed in code. I guess one of them likely be not following 72 character width limit.  I will also read again PEP8 and try to find inconsistencies. Also some of the style guide I follow come from:
* [Adam Tornhill - Code that fits your brain]( https://vimeo.com/97471514)
* [Kevlin Henney - Seven Ineffective Coding Habits of Many Programmers](https://vimeo.com/97329157)
* [Martin Fowler - Software Design in the 21st Century](https://www.youtube.com/watch?v=6wDoopbtEqk)

Some of these likely would not be present in PEP8 or inconsistent with it. Such as, all arguments must be in one line or else each argument split on different line. And only first character of acronym should be capitalized eg. parseHtml and not parseHTML. I will commit documentation wiki after some cleaning up which includes style guide for project. Where PEP8 and other guidelines are found to be in contradiction, we will discuss and choose one that is best for project and community.

Welcome to the team :)

**Comment by srevinsaju** [comment]
Thanks, I will work on this issue and make it PEP8 compatible. To know what are the mistakes / code style which you haven't followed, please use `flake8`, to see which of the rules are not followed in your code. I tried reading your code, and I thought I would refactor it as well, but the code was too complex. I will address this in a PR

**Comment by radiidev** [comment]
The code is checked with flake8 except 3 comment remarks and 4 likely false-positive of indentation after multi-line condition & parameter.

**Comment by srevinsaju** [comment]
Ok, I will check it out, thanks for the quick response

------------

As an aside, are you in the AEST time zone? If not which time zone are you, so that I can work with you more effectively

**Comment by radiidev** [comment]
Yes, AEST/AEDT.
